Quickstart for the impatient
============================

Requisites:

  Depending on what repositories you want to generate, you can install
  a combination of these packages:

	tool		package		provides
	""""		"""""""		""""""""
	genbasedir	apt		provides apt support
	yum-arch	yum		provides yum support
	createrepo	createrepo	provides repomd support (new yum, new apt)

  Depending on what kind of sources you want to mirror, you can install
  a combination of these packages:

	tool		provides
	""""		""""""""
	rsync		provides rsync:// access
	lftp		provides ftp://, http://, sftp:// fish://


Do the following steps to get started (real) fast.

  1. Edit /etc/mrepo.conf and add for each distribution a new section
     like the examples given in the default mrepo.conf, mrepo-complex.conf
     or mrepo-example.conf

     You can add a distribution section to a new file in /etc/mrepo.conf.d/

		eg. /etc/mrepo.conf.d/fc3-i386.conf

     See the examples in the documentation as a reference.


  2. If you want to add your own custom packages to one or all of
     the repositories, you have 2 options.

     a. Add them to /var/mrepo/<distro>-<arch>/local/

		eg. /var/mrepo/fc3-i386/local/

	or add them to /var/mrepo/all/local/ to add them to all.

     b. Specify the directory of your choice in a new repository,
	eg. called 'myrepo'

		[fc3-i386]
		name = Fedora Core $release ($arch)
		release = 3
		.
		.
		myrepo = file:///var/ftp/pub/my-rpms/fc3/i386/

	eg. you can rewrite this as:

		myrepo = file:///var/ftp/pub/my-rpms/$dist/$arch/

        This way you can specify an unlimited number of custom
        repositories.


  3. Now run mrepo to update the repositories:

	mrepo -uvv

     Then generate the mrepo repositories by doing:

	mrepo -gvv

     Now look in $wwwdir (normally /var/www/mrepo) or surf to
     http://localhost/mrepo/ to see if everything is the way you wanted.


  4. Next time you can do directly

	mrepo -ug
     or
	mrepo -ugv

     and all steps will be performed in one phase.


  5. When you're adding new distributions, it's sufficient to just
     run mrepo again.

---
Please send me improvements to this document.
