Quickstart for the impatient
============================

Requisites:

  Depending on what repositories you want to generate, you can install
  a combination of these packages:

	tool		package		provides
	""""		"""""""		""""""""
	createrepo	createrepo	provides repomd support (new yum, new apt)

  Depending on what kind of sources you want to mirror, you can install
  a combination of these packages:

	tool		provides
	""""		""""""""
	rsync		provides rsync:// access
	lftp		provides ftp://, http://, sftp:// fish://


Do the following steps to get started (real) fast.

  1. Edit /etc/mrepo.conf and add for each distribution a new section
     like the examples given in the default mrepo.conf, mrepo-complex.conf
     or mrepo-example.conf

     You can add a distribution section to a new file in /etc/mrepo.conf.d/

		eg. /etc/mrepo.conf.d/fc3-i386.conf

     See the examples in the documentation as a reference.


  2. Now run mrepo to update the repositories:

	mrepo -uvv

     Then generate the mrepo repositories by doing:

	mrepo -gvv

     Now look in $wwwdir (normally /var/www/mrepo) or surf to
     http://localhost/mrepo/ to see if everything is the way you wanted.


  3. Next time you can do directly

	mrepo -ug
     or
	mrepo -ugv

     and all steps will be performed in one phase.


  4. When you're adding new distributions, it's sufficient to just
     run mrepo again.

---
Please send me improvements to this document.
