name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.9
    - uses: actions/checkout@v4
    - name: Run Unit Tests
      run: python runtests.py
